// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjBUPEgrN-pRQUGh7zyQdq9deTB2Ct9k',
    appId: '1:599086093492:web:a0741f55e165095b0db3e1',
    messagingSenderId: '599086093492',
    projectId: 'cantina-aman-62e5d',
    authDomain: 'cantina-aman-62e5d.firebaseapp.com',
    storageBucket: 'cantina-aman-62e5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrsEFOy9Ty4P9UNQP6XQphOoQ-VKle7PQ',
    appId: '1:599086093492:android:7f4447ff7669cb760db3e1',
    messagingSenderId: '599086093492',
    projectId: 'cantina-aman-62e5d',
    storageBucket: 'cantina-aman-62e5d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWjBUPEgrN-pRQUGh7zyQdq9deTB2Ct9k',
    appId: '1:599086093492:web:ed3a8d89b08016b00db3e1',
    messagingSenderId: '599086093492',
    projectId: 'cantina-aman-62e5d',
    authDomain: 'cantina-aman-62e5d.firebaseapp.com',
    storageBucket: 'cantina-aman-62e5d.firebasestorage.app',
  );
}
